name: e_pesan_resto
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  awesome_dialog: ^3.2.1
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.16
  get: ^4.6.6
  intl: ^0.18.0
  shared_preferences: ^2.1.0
  flutter_spinkit: ^5.2.1
  internet_connection_checker: ^0.0.1
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins_Regular.ttf
        - asset: assets/fonts/Poppins_SemiBold.ttf
        - asset: assets/fonts/Poppins_Bold.ttf
        - asset: assets/fonts/Poppins_Thin.ttf
